require:
- rubocop-performance
- rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: true

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Lint/EmptyFile:
  Enabled: false